print ('Olá, informe de acordo como o solicitado: ')
dia = input ('Em que dia você nasceu? ')
mes = input ('Em que mês que nasceu ?')
ano = input ('Em que ano você nasceu? ')
print ('Sua data de aniversario é:', dia,'/', mes ,'/', ano ,', Correto?')
resposta = input ('Insira sua resposta aqui = ')
print ('Obrigado pelas informações!')
