x = input('Digite algo: ')
print('O tipo primitivo desse valor é',type(x))
print('Só tem espaço? ',x.isspace())
print('Está em maiúsculas? ',x.isupper())
print('Está em minúsculas? ',x.islower())
print('Ele é alfanumérico? ',x.isalnum())
print('É alfabético? ',x.isalpha())
print('É um número? ',x.isnumeric())
print('Está capitalizada? ',x.istitle())
